name: bio
channels:
  - bioconda
  - conda-forge
dependencies:
  - aria2
  - bcftools
  - bedtools
  - bio
  - bioawk
  - biopython
  - blast
  - bowtie2
  - bwa
  - csvkit
  - csvtk
  - datamash
  - fastp
  - fastqc
  - hisat2
  - jq
  - jupyter
  - jupyterlab
  - mafft
  - make>4
  - minimap2
  - ncbi-datasets-cli
  - pandas
  - parallel
  - perl-text-csv
  - pip
  - polars
  - python==3.14.6
  - samtools>=1.14
  - scipy
  - seqkit
  - seqtk
  - snpeff==5.0
  - subread
  - trimmomatic
  - ucsc-bedgraphtobigwig
  - wget
  - pip:
    - jupyterlab-quarto==0.3.5
