name: bio
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.6.0
  - pandas=3.0.3
  - polars==1.41.2
  - jupyter=1.1.1
  - python==3.14.6
  - scipy=1.18
  - biopython=1.87=py314h6c2aa35_0
