# Study Plan for Bioinformatics

This is a **PRELIMINARY** study plan.

I currently envision a two-pronged approach:

1) ***Get an overview of the field***.  See Main Text and Supplemental Texts section below.  Especially when using the Biostart handbook, practice using the tools (hacking), most likely in QMD notebooks but also in Makefiles or Taskfiles or the like plus Python source as appropriate. 
2) ***Do Exploratory Research in Alcohol Use Disorder*** This is a topic of interest, and we can use it to practice in the context of a real project.
3) Improve my R Skills, see Modern Statistics with R. 
### Main Text for an Overview:

The [Biostar Handbook](https://biostar.myshopify.com/).  $35.00 with two year access, $25.00 for one month.  Go through this and the associated course, FastTrack Bioinformatics.  Just reading the titles has helped me already.  Should do this 1st.

### Supplemental Texts:

1. Introduction to Bioinformatics.  Arthur M. Lesk. Ordered an older edition from Thriftbooks.  See [Gemini's assessment](https://share.gemini.google/8TrW8WBwm6lZ).
2. [Bioinformatics Data Skills](https://www.amazon.com/Bioinformatics-Data-Skills-Reproducible-Research/dp/1449367372) by Vince Buffalo.  Currently $42.20 new.  Not sure if we'll need to add this, but it has lots of folks recommending it.  Might be a lot of overlap with Biostar Handbook.


### My original Plan (Legacy)

To quote a controversial politico when asked when he had a plan:

> I have a concept of a plan.

Possibilities include:

* Work through Discovering Statistics Using R.  The edition I have is out of date, but cost $70 or more back then, and the new edition costs that now.  Out of date is better than ignorant.  You can get a lot of the source for the updated book [for free, here](https://www.discovr.rocks/)
* Take Harvard/EdX's course [Data Analysis for Life Sciences](https://www.edx.org/certificates/professional-certificate/harvardx-data-analysis-for-life-sciences).  This was a [Gemini recommendation](https://gemini.google.com/app/2f5aa9c02d73575b)
* ChatGPT's [recommendation](https://chatgpt.com/c/6a37c788-6d84-83ea-9fff-59a9463e51bd) was more tilted toward Python, which is where a lot of the work seems to be headed currently.  See especially the section "If I were starting today".  Especially relevant were the idea of using Pevzner's Bioinformatics Algorithms (copy saved in Thriftbooks, but it's heavy on algorithms, so holiding off and it may be sold out of my cart -- but it's also available on [Coursera](https://www.coursera.org/specializations/bioinformatics)) and using [Rosalind](https://rosalind.info).  Registered using BioJohnsin username.
