---
title: "Chapter 1 Notes"
author: "John Lockwood"
format: html
editor: visual
---

These are notes are based on *Discovering Statistics Using R*, part of my [Statistics 1](../DiscoveringStatisticsUsingR/Statistics_01.qmd) course.

## Well, here we are

This chapter gets into "Why Statistics", with some entertaining arm-waving about how answering questions in the sciences often involves processing "quantitative methods." There's also a flow chart about the research process, which the rest of the chapter goes through. It starts to get interesting as he develops theories about why game show contestants have narcissistic personality disorder, and shows a data table. A good theory should generate testable — ideally falsifiable — hypotheses.

Moves on to discussing data collection. When we do this we need to figure out:

1\) What to measure.

2\) How to measure it.

### What to Measure

Independent vs dependent variables. If we think one thing causes another, the cause an independent variable. The thing it causes is the dependent variable. Especially use these terms when we use experimental methods, because we can manipulate the variables. More generally, a predictor variable corresponds to independent variable and outcome variable refers to a dependent variable, so we can also use in corelational or cross-sectional research where we don't manipulate variables. These terms don't imply causation as strongly.

Categorical variables (enums, more or less), vs continuous variables (real (or at least natural) numbers). Some categories are binary variables (male/female, alive/dead). Of course, categories can also be represented by numbers.

Ordered categories are ordered (e.g. contest winners could be labeled first, second, third, etc) nominal categories are just names and don't tell us about ordering (Bob, Jane, Phred with a ph).

Continuous variables include interval variables. "To say that data are interval, we must be certain that equal intervals on the scale represent equal differences in the property being measured." E.g. rating scales, 3 vs 4 same as 4 vs 5 (but some self-report scales are more subjective and therefore ordinal? ). Discussion is confusing. Ratio variables are interval variables with the added condition that ratios are meaningful. A professor rated 4 is twice as helpful as one rated 2. Reaction time as a better example, the ratio of 500 ms to 400 ms is the same as 1000:800 ms.

Continuous variables can be measured discretely. E.g. age is measured in years, not in hours or picoseconds.

Measurement errors. Could be from improperly calibrated equipment, differences in measurement equipment, and notoriously true of self-reported data, where people may be interested in protecting their reputation, saying what they expect the researchers want, etc. etc.

Validity vs reliability. Validity: Did the measurement really report what it was designed to measure? Reliablitity: Is it consistent in its measurements.

### Data Collection: How to Measure

#### Correlational Research

AKA cross-sectional research. Where we observe what naturally happens in the world.

Correlational research has problems establishing cause, often because of a **tertium quid** (third thing) that is related to and perhaps causes both what we considered the cause and the effect, or perhaps that causes the effect independently of the cause. These extra factors are also sometimes called **confounding variables** or simply confounds.

#### Experimental Research

Where we manipulate one variable to see its effect on another. Often we're looking to eliminate confounding effects by making sure we don't see an effect absent the cause, so we test with the cause and without it.

### Two methods of data collection:

1.  Called "between-groups", or "between-subjects" or "independent design". We manipulate the independent variable by having two different groups of subjects.
2.  Called "whithin-subjects" or "repeated measures design." E.g. take the same group and give them negative reinforcement for a period of weeks and test performance, and then in a subsequent period(s) give them positive or no reinforcement (or both), and compare the performance.

### Two types of variation

1.  If the same subject performs slightly differently on the same test under the same conditions at different times, this is **unsystematic variation**.
2.  If we change the conditions between one run and the next, then (you guessed it), this is **systematic variation**.

Same things happen in groups of different participants. Given the same test to two groups, one group will do better than the other do to individual differences. This is unsystematic.

But there are always both things going on, in any test, so the role of statistics is to sort out how much is due to individual (or group) differences, and how much do to the manipulated independent variable.

We try to minimize the influence of unsystematic variation by **randomization**. In repeated measure design, you can minimize the effects of boredom (negative) and practice effects (i.e. learning, positive), by changing the order of sessions for different participants (i.e experiment vs control first). This is called **counterbalancing** the order. In independent design, you need to ensure that you select your groups randomly, especially with respect to any confounding variables.

### Frequency distributions

When you have data, it's useful to do a histogram of the frequency of different values. One way these can be distributed is a normal distribution, the good ol' bell curve. Height is a good example.

Two ways to vary from normal distribution are: 1. **Skew**, where values cluster to the left or right of center. Note (this is counter-intuitive) positively skewed means the **tail** points to the right, so the hump is on the left. Negative skew is where the tail points to the left, so hump is in the right. 2. **Kurtosis** has to do with how pointy the distribution is and how many clusters are in the tails. A tall pointy distribution with heavy tails is **leptokurtic**, or has **positive kurtosis**. A more boxy, confused disturbutions with highs throughout, flatter than normal, has negative kurtosis or is **platykurtic**.

### The center of a distribution

We can use three diffferent measures for center.

The mode occurs most frequently, i.e. the tallest bar of our histogram.

(Interlude: Where's my histogram? Come on, Andy, where's my code? I guess we don't get to do R just yet. Talking makes programmers sad. Be patient, grasshopper.)

Mean, mode, and median. Mean is the arithmetic average found in the usual way:

$$\frac{\sum\limits_{1 \to n}}{n}$$ The median is (more or less) a score such that 50% of values are below, and 50% above. Formally, we arrange in ascending order, count the number of scores, add one to the count, and divide by two. This gives the index of the median score. For an odd number, works out great. For an even number, let's say 10 scores

$$\frac{10 +1}{2} = 5.5$$

which is midway between scores 5 and 6 so we average those to scores and that's the median.

The mode is the value that occurs most often

Let's use the example he gives and try our hand at some R code. (You can't keep a good man down — and programmers neither.) Google tells us that Tidyverse simply uses R arrays in the one dimensional case, so here are the values he gives, the mean and the mode.

```{R}
# Since I pirated these values from the text, we'll give them a pirate name
arr <- c(108, 103, 252, 121, 93, 57, 40, 53, 22, 116, 98)

cat("Array length:\n")
print(length(arr))

cat("\nMedian value\n")
median(arr)

cat("\nMean value\n")
round(mean(arr), 2)
```

The results I got were consistent with the book. Since there's no repeating value, mode is undefined, and it turns out R's built-in mode function simply returns the data type of the array, "numeric" in this case. However, a Google search suggested this code doing a descending order sort on a table and selecting the first value:

```{R}
my_array <- c(1, 2, 2, 3, 4, 2, 5)
# Returns the name of the highest-frequency element
names(sort(-table(my_array)))[1] 
```

That returns two, as expected. Google cautions against using this code however for general cases, and we can easily see that it fails to handle the case where the length \>= 2 and the first two values are the same, where mode is undefined. We would also need to consider the trivial one-element case.

June 25, 2026\
We begin today by just doing the self-test, which in R amounts to removing the 252 value and re-running the mean. By way of R pedagogy, let's see if we can do that with respect to arr:

```{r}
# Original arr
arr <- c(108, 103, 252, 121, 93, 57, 40, 53, 22, 116, 98)
arr

# Use a negative index to remove value at position 3
short_arr <- arr[-3]
short_arr

print(round(mean(short_arr), 2))
```

OK, my little excuRsion agreed with the text, cool. The point of this was to show that compared to the median, the mean is sensitive to outliers.

He next shows how to get the **range**, which is just the difference between the min and max value. This is easy enough to find in R through the usual procedure of "guess how to do it and run it to see if it works." (Statements like that is why other senior engineers used to object to me sharing their title back in the days when that's what I was doing).

```{R}
arr <- c(108, 103, 252, 121, 93, 57, 40, 53, 22, 116, 98)
short_arr <- arr[-3]

print("Showing the range for the original array")
range_long = range(arr)
print(range_long)
print(diff(range_long))

# For the self test the range is much smaller
print("For the self test the range is much smaller")
range_short = range(short_arr)
print(range_short)
print(diff(range_short))

```

Gemini [pointed out](https://share.gemini.google/YkD6RjeRtWjB) that that code can be improved for large data sets, where it tends to be inefficient, and provided another way to do it.

### Quartile Data

Quartiles are three values that split the range into four equal parts. First, we calcluate the median, which splits the data into two eauql parts. The lower quartile is the median of the lower half, and the upper quartile is the median of the lower half.

Can we accomplish this in R easily? I would imagine so. We can use the quantile function.

```{R}
arr <- c(108, 103, 252, 121, 93, 57, 40, 53, 22, 116, 98)
print(length(arr))
sorted_arr = sort(arr) # Show the sorted array
print(sorted_arr)
print(quantile(arr)) # Use the original, quantile will sort for us

# Next we'll show the inter-quartile range, which Fields discusses next.
IQR(arr)
IQR(arr, type=1) # How to match the book's answer.
```

Note that the values obtained sing quantile are intermediate between actual values, the true medians. Perhaps before I finish up the chapter I'll write a function to subset the array appropriately (R has "cut" function, but I'm not sure that's fit for this purpose).

Along similar lines, I've printed out the IQR twice here. Using type=1 gets an answer that will agree with the textbook, which uses actual values from the array. Using the default uses the quantile function under the hood, which gives interpolated values, (i.e. 57 = 112-55). For background see \[this Gemini response\](<https://share.gemini.google/2xcibEUZqR28>) and the [IQR documentation](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/IQR)

Next, let's do the self-test using R. Again, in the textbook, we haven't gotten to R yet, I'm skipping ahead. The book is aimed at undergrads who haven't learned to program yet, not old guys who used to do it for a living.

The self test asks us to compute several values for an array of values, representing the time in seconds that a group of heavy smokers put on a treadmill fell off from exhaustion. Let's set that up and solve it using R defaults.

```{R}
data <- c(18, 16, 18, 24, 23, 22, 22, 23, 26, 29, 32, 34, 34, 36, 36, 43, 42, 49, 46, 46, 57)
# print(data)

# We're asked to compute the mode, median, mean, upper and lower quartiles, range, and interquartile range.

# Let's first print the sorted data to give us an idea of what's going on.
s_data <- sort(data)
cat("Data:", s_data)

# No value occurs "the most times", though if I had to guess I'd say something between 34 aand 36, which both appear twice, as do 22 and 46
cat("\nNo mode")

# The rest of the tasks are straightforward if we focus on using R rather than matching whatever value Andy publishes (see discussion above.)
cat(sprintf("\nMean: %.2f", mean(data)))
cat(sprintf("\nMedian: %.2f", median(data)))
cat("\nQuartiles:\n")
print(quantile(data))
cat(sprintf("Inter-quartile range: %.2f\n", IQR(data)))
```

In the next section he discusses how probable it is that something could happen, using suicide data to show that most suicides occur between the ages of 30-35 (which isn't borne out here in US by real data, I think). There's more to do in this section, but we'll leave it there for today.

\
