---
title: The Bioinformatics of Alcoholism
author: John Lockwood
format: revealjs
---

## Overview

- Bioinformatics of Alcoholism (Alcohol Use Disorder, Alcohol Dependence)

  - Some basic definitions  
		(Biology 101 condensed into 5-10 minutes)

  - Genetic "Causes" or Alcoholism

  - Effects

- Simplified Overview

## Some basic definitions...

A really short course in biology taught by someone with no business teaching a longer course.

## Genes and the genome

***The Genome***

- The whole DNA that you need to create an organism.
- Imagine a book written on a long string of beads (DNA is double stranded)
- Individual beads (letters of the book) are called nucleotides or bases.  For a human you need about 3.2 billion letters.
- Names of the bases start with letters, ACTG.

## Gene:  

* A part of the genome (call it a page from the book or a chapter) that contains the code for "a single protein."
* Some parts of the gene say how to build a protein, other parts control how much protein gets created (regulation).  
* Other parts do nothing, are leftovers from evolution, or are not yet understood.

## More definitions

***Central Dogma of Biology:***

$\boxed{ \text{DNA (the genome)}} \rightarrow \boxed{\text{Expression:  RNA} \rightarrow \text{ Proteins}}$

- DNA almost everywhere.
- What gets expressed changes depending on:
  - cell type
  - stage of development
  - environment (e.g. stress, chemicals ingested)

## How this looks ("sequenced DNA")

The Human Genome Project was an attempt to translate this string of biochemical "nucleotides" (all 3.2 billion) into letters representing each one. "Completed" in 2000-2003.

How it looks (for part of one gene):

> >NP_000798.2 {"type": "CDS", "gene": "GABRA2", "product": "gamma-aminobutyric acid receptor subunit alpha-2 isoform a precursor", ...}
ATGAAGACAAAATTGAACATCTACAACATGCAGTTCCTGCTTTTTGTTTTCTTGGTGTGG
GACCCTGCCAGGTTGGTGCTGGCTAACATCCAAGAAGATGAGGCTAAAAATAACATTACC 
... + 485 more lines !

## Causes:  Genetics of Alcoholism

It's estimated that genetics  accounts for some 50-60% of the risk of developing alcoholism, with 40-50% of risk coming from environment: "childhood trauma, chronic stress, peer groups, and early exposure to drinking."

***IMPORTANT:  We are not talking about a single alcohol gene here.***

Alcoholism is **Polygenic** (Caused by many genes).  Most traits and diseases are polygenic.

## Other Examples
* Polygenic traits and diseases:  Heart disease, Height, Type 2 Diabetes, Impulsiveness, High Blood Pressure, Diabetes, Schizophrenia, Bipolar Disorder etc. etc.  Most genetic conditions/traits are like this.
* Some monogenic diseases:  Sickle Cell Disease, Tay Sachs, Cystic Fibrosis.
* In the case of alcoholism, about 100 or more different genes affect your level of susceptibility.  (As of now -- we may learn more)

## Genes Involved In Alcoholism (Part I)

* Variations in genes that relate to how fast body metabolizes alcohol.  Two variations (more common in Asian populations) cause either an unpleasant flushing response or people get extremely ill.  (Very much like Antabuse).  These genes are considered *protective*.
* The opposite problem above is people who are highly tolerant of alcohol. They can at first drink quite a bit without getting sick.  We say they are "Low Level of Response", and this is considered to strongly predispose an individual to alcoholism.  


## Genes Involved In Alcoholism (Part II)

* Variations in genes that control "impulsiveness".  Impulsiveness is itself 
regulated by several genes in interaction with the environment.  People who are 
more impulsive are inclined to take more risks early in life -- to drink and 
to drink more than others.  Early drinking in turn itself is a risk factor.
* Variations in a gene that relates to how strongly we react to bitter tastes.
* My personal favorite gene is GABRA2, which encodes one of the parts (the $\alpha$ subunits) of the GABA receptor.


## GABA and GABA Receptors

* We're not biochemists, but what the heck:  GABA stands for $\gamma$ (Gamma) 
Amniobutyric Acid.
* For our purposes what's important is that it's a neurotransmitter, naturally occurring in our brains, that:
  * Inhibits nerve cells (makes it less likely that they'll fire).
  
  



## Effects (How the Body Responds)

## Additional resources

* Something something.